### ISSUE TITLE
Parallel Training

### ISSUE THREAD

**Issue by eternal-f1ame** [ziqi-jin/finetune-anything#25]
When training on 4 GPUs (Tesla K-80 11441MiB)
my bs = 4 and workers = 4
but I always end up with the error

RuntimeError: CUDA error: the launch timed out and was terminated (is there a work around or is it due to my compute limitations)

**Comment by ziqi-jin** [comment]
> When training on 4 GPUs (Tesla K-80 11441MiB) my bs = 4 and workers = 4 but I always end up with the error
> 
> RuntimeError: CUDA error: the launch timed out and was terminated (is there a work around or is it due to my compute limitations)

Hi, I tested four cards in parallel, and the maximum space required for each card is 8895MB. Your problem may be caused by other reasons.

**Comment by eternal-f1ame** [comment]
Yeah it was a cuda bug in my server (Ubuntu 20.04, CUDA:11.4).
Wasnt resolved but I shifted to another server (Ubuntu 18.04, CUDA: 11.4) and it works.
