### ISSUE TITLE
RuntimeError: CUDA error: device-side assert triggered

### ISSUE THREAD

**Issue by jiaweichaojwc** [ziqi-jin/finetune-anything#46]
我使用我的数据集来进行微调，但是出现了以下错误
img_folder_name: /mnt/hdd0/jwc/代码仓/finetune-anything/Datasetv1/train-and-val/train/images, ann_folder_name: /mnt/hdd0/jwc/代码仓/finetune-anything/Datasetv1/train-and-val/train/class_labels
img_folder_name: /mnt/hdd0/jwc/代码仓/finetune-anything/Datasetv1/train-and-val/val/images, ann_folder_name: /mnt/hdd0/jwc/代码仓/finetune-anything/Datasetv1/train-and-val/val/class_labels
/pytorch/aten/src/THCUNN/SpatialClassNLLCriterion.cu:106: cunn_SpatialClassNLLCriterion_updateOutput_kernel: block: [11,0,0], thread: [503,0,0] Assertion `t >= 0 && t < n_classes` failed.
/pytorch/aten/src/THCUNN/SpatialClassNLLCriterion.cu:106: cunn_SpatialClassNLLCriterion_updateOutput_kernel: block: [11,0,0], thread: [504,0,0] Assertion `t >= 0 && t < n_classes` failed.
/pytorch/aten/src/THCUNN/SpatialClassNLLCriterion.cu:106: cunn_SpatialClassNLLCriterion_updateOutput_kernel: block: [11,0,0], thread: [476,0,0] Assertion `t >= 0 && t < n_classes` failed.
/pytorch/aten/src/THCUNN/SpatialClassNLLCriterion.cu:106: cunn_SpatialClassNLLCriterion_updateOutput_kernel: block: [11,0,0], thread: [477,0,0] Assertion `t >= 0 && t < n_classes` failed.
/pytorch/aten/src/THCUNN/SpatialClassNLLCriterion.cu:106: cunn_SpatialClassNLLCriterion_updateOutput_kernel: block: [11,0,0], thread: [608,0,0] Assertion `t >= 0 && t < n_classes` failed.
/pytorch/aten/src/THCUNN/SpatialClassNLLCriterion.cu:106: cunn_SpatialClassNLLCriterion_updateOutput_kernel: block: [11,0,0], thread: [609,0,0] Assertion `t >= 0 && t < n_classes` failed.
/pytorch/aten/src/THCUNN/SpatialClassNLLCriterion.cu:106: cunn_SpatialClassNLLCriterion_updateOutput_kernel: block: [11,0,0], thread: [610,0,0] Assertion `t >= 0 && t < n_classes` failed.
/pytorch/aten/src/THCUNN/SpatialClassNLLCriterion.cu:106: cunn_SpatialClassNLLCriterion_updateOutput_kernel: block: [11,0,0], thread: [611,0,0] Assertion `t >= 0 && t < n_classes` failed.
/pytorch/aten/src/THCUNN/SpatialClassNLLCriterion.cu:106: cunn_SpatialClassNLLCriterion_updateOutput_kernel: block: [11,0,0], thread: [612,0,0] Assertion `t >= 0 && t < n_classes` failed.
/pytorch/aten/src/THCUNN/SpatialClassNLLCriterion.cu:106: cunn_SpatialClassNLLCriterion_updateOutput_kernel: block: [11,0,0], thread: [613,0,0] Assertion `t >= 0 && t < n_classes` failed.
/pytorch/aten/src/THCUNN/SpatialClassNLLCriterion.cu:106: cunn_SpatialClassNLLCriterion_updateOutput_kernel: block: [11,0,0], thread: [614,0,0] Assertion `t >= 0 && t < n_classes` failed.
/pytorch/aten/src/THCUNN/SpatialClassNLLCriterion.cu:106: cunn_SpatialClassNLLCriterion_updateOutput_kernel: block: [11,0,0], thread: [576,0,0] Assertion `t >= 0 && t < n_classes` failed.
/pytorch/aten/src/THCUNN/SpatialClassNLLCriterion.cu:106: cunn_SpatialClassNLLCriterion_updateOutput_kernel: block: [11,0,0], thread: [577,0,0] Assertion `t >= 0 && t < n_classes` failed.
/pytorch/aten/src/THCUNN/SpatialClassNLLCriterion.cu:106: cunn_SpatialClassNLLCriterion_updateOutput_kernel: block: [11,0,0], thread: [602,0,0] Assertion `t >= 0 && t < n_classes` failed.
/pytorch/aten/src/THCUNN/SpatialClassNLLCriterion.cu:106: cunn_SpatialClassNLLCriterion_updateOutput_kernel: block: [11,0,0], thread: [603,0,0] Assertion `t >= 0 && t < n_classes` failed.
/pytorch/aten/src/THCUNN/SpatialClassNLLCriterion.cu:106: cunn_SpatialClassNLLCriterion_updateOutput_kernel: block: [11,0,0], thread: [604,0,0] Assertion `t >= 0 && t < n_classes` failed.
/pytorch/aten/src/THCUNN/SpatialClassNLLCriterion.cu:106: cunn_SpatialClassNLLCriterion_updateOutput_kernel: block: [11,0,0], thread: [605,0,0] Assertion `t >= 0 && t < n_classes` failed.
/pytorch/aten/src/THCUNN/SpatialClassNLLCriterion.cu:106: cunn_SpatialClassNLLCriterion_updateOutput_kernel: block: [11,0,0], thread: [606,0,0] Assertion `t >= 0 && t < n_classes` failed.
/pytorch/aten/src/THCUNN/SpatialClassNLLCriterion.cu:106: cunn_SpatialClassNLLCriterion_updateOutput_kernel: block: [11,0,0], thread: [607,0,0] Assertion `t >= 0 && t < n_classes` failed.
Traceback (most recent call last):
  File "/mnt/hdd0/jwc/代码仓/finetune-anything/train.py", line 45, in <module>
    runner.train(train_cfg)
  File "/mnt/hdd0/jwc/代码仓/finetune-anything/extend_sam/runner.py", line 62, in train
    self._compute_loss(total_loss, loss_dict, masks_pred, labels, cfg)
  File "/mnt/hdd0/jwc/代码仓/finetune-anything/extend_sam/runner.py", line 127, in _compute_loss
    loss_dict[item[0]] = tmp_loss.item()
RuntimeError: CUDA error: device-side assert triggered
我要是只使用一部分数据集就没有这个问题，但是当我将完整数据集进行训练的时候，就出现了上面的问题，我的标签是0-12,255，类别数写的13，忽略了255这个数值，因为我的代码能力并不是很强，作者的工作非常优秀，你能给我一些指导吗？帮我解决一下这个问题，希望作者有时间给予一个回复，谢谢！

**Comment by jiaweichaojwc** [comment]
当我将模型部署到cpu上运行时出现了以下错误：
(fa) jwc@oem-SYS-7048GR-TR:~/代码仓/my_scripts-finetun-anything$ python train.py --cfg /mnt/hdd0/jwc/代码仓/my_scripts-finetun-anything/config/semantic_seg_securitydataset.yaml
img_folder_name: /mnt/hdd0/jwc/代码仓/my_scripts-finetun-anything/Datasetv1/train-and-val/train/images, ann_folder_name: /mnt/hdd0/jwc/代码仓/my_scripts-finetun-anything/Datasetv1/train-and-val/train/class_labels
img_folder_name: /mnt/hdd0/jwc/代码仓/my_scripts-finetun-anything/Datasetv1/train-and-val/val/images, ann_folder_name: /mnt/hdd0/jwc/代码仓/my_scripts-finetun-anything/Datasetv1/train-and-val/val/class_labels
Target range: tensor(0) - tensor(255)
Traceback (most recent call last):
  File "/mnt/hdd0/jwc/代码仓/my_scripts-finetun-anything/train.py", line 46, in <module>
    runner.train(train_cfg)
  File "/mnt/hdd0/jwc/代码仓/my_scripts-finetun-anything/extend_sam/runner.py", line 62, in train
    self._compute_loss(total_loss, loss_dict, masks_pred, labels, cfg)
  File "/mnt/hdd0/jwc/代码仓/my_scripts-finetun-anything/extend_sam/runner.py", line 170, in _compute_loss
    tmp_loss = item[1](mask_pred, real_labels)
  File "/home/jwc/anaconda3/envs/fa/lib/python3.9/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/jwc/anaconda3/envs/fa/lib/python3.9/site-packages/torch/nn/modules/loss.py", line 961, in forward
    return F.cross_entropy(input, target, weight=self.weight,
  File "/home/jwc/anaconda3/envs/fa/lib/python3.9/site-packages/torch/nn/functional.py", line 2468, in cross_entropy
    return nll_loss(log_softmax(input, 1), target, weight, None, ignore_index, None, reduction)
  File "/home/jwc/anaconda3/envs/fa/lib/python3.9/site-packages/torch/nn/functional.py", line 2266, in nll_loss
    ret = torch._C._nn.nll_loss2d(input, target, weight, _Reduction.get_enum(reduction), ignore_index)
IndexError: Target 26 is out of bounds.
然后增加了两条打印信息
![image](https://github.com/ziqi-jin/finetune-anything/assets/113352745/f57eb7cd-88e6-40cd-b5c3-c448f8d79caa)
之后出现了
![image](https://github.com/ziqi-jin/finetune-anything/assets/113352745/38dcae8a-7fc3-4a25-b510-1a0b828f1a02)
但是我读取过我的标签数据，是0-12和255，现在打印了一下labels，结果是0-255，我直接不清楚问题所在了，我只看到了resize的数据预处理，不应该会出现0-255内的所有数呀

**Comment by shhjjj** [comment]
请问你解决这个问题了吗，我也遇到了同样的问题

**Comment by jiaweichaojwc** [comment]
@shhjjj 已经解决了，主要是标签在经过程序之后变了，我的标签是0-12和255，但是使用程序预处理后使用的是双线性插值造成标签变成了0-255的所有数，标签类别无缘无故增加了，造成索引越界的问题，希望可以帮到你
